In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv('Books.csv')
ratings = pd.read_csv('Ratings.csv')
users = pd.read_csv('Users.csv')

C:\Windows\Temp\ipykernel_10412\378180666.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [5]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [6]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [7]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

# Shape of Dataset ❓

In [8]:
print("The shape of book is    : ",books.shape)
print("The shape of ratings is : ",ratings.shape)
print("The shape of users is   : ",users.shape)

The shape of book is    :  (271360, 8)
The shape of ratings is :  (1149780, 3)
The shape of users is   :  (278858, 3)

# Nan value in Dataset ❓

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [11]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

# Duplication in Dataset ❓

In [ ]:
books.duplicated().sum()

np.int64(0)

In [ ]:
users.duplicated().sum()

np.int64(0)

In [15]:
ratings.duplicated().sum()

np.int64(0)

# Popularity Based Recommender system Top 50 books
1. minimum 250 votes

In [16]:
ratings_with_name = ratings.merge(books, on='ISBN')

In [17]:
ratings_with_name.head(2)

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...

In [18]:
print("The shape of ratings with name : ",ratings_with_name.shape)

The shape of ratings with name :  (1031136, 10)

In [19]:
ratings_with_name.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [20]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

# Average rating

In [21]:
ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [22]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

# num rating > 250

In [23]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [24]:
popular_df

,Book-Title,num_ratings,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [25]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[
    ['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_rating']
    ]

In [27]:
popular_df.head(10)

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000

# user should be rating minimum = 200
# books rating minimum = 50

# # collaboration filtering based recommender system

In [28]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [29]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
experienced_users = x[x].index

In [30]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(experienced_users)]

In [31]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

In [32]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [33]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [34]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [35]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...,...,...
1029196,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...
1029197,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...
1029270,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...
1029309,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...
1029310,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...

In [36]:
print("The shape of final ratings : ",final_ratings.shape)

The shape of final ratings :  (58586, 10)

In [37]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...,...,...
1029196,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...
1029197,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...
1029270,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...
1029309,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...
1029310,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...

# pivot table

In [38]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [39]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [40]:
pt.fillna(0,inplace=True)

In [41]:
pt.head()

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# **cosine similarity**

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity_scores = cosine_similarity(pt)

In [44]:
similarity_scores.shape

(706, 706)

In [45]:
similarity_scores[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [46]:
list(enumerate(similarity_scores[0]))
# distance + items

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.10255024829874466)),
 (2, np.float64(0.012208555646509366)),
 (3, np.float64(0.0)),
 (4, np.float64(0.053672244225442485)),
 (5, np.float64(0.027749013024662858)),
 (6, np.float64(0.08216491130000354)),
 (7, np.float64(0.13732869060263378)),
 (8, np.float64(0.03261686350494277)),
 (9, np.float64(0.03667590746512177)),
 (10, np.float64(0.02322418425912186)),
 (11, np.float64(0.06766486753662343)),
 (12, np.float64(0.020839782065795794)),
 (13, np.float64(0.09673734976610586)),
 (14, np.float64(0.13388864701187034)),
 (15, np.float64(0.0830311169181103)),
 (16, np.float64(0.1115354275858341)),
 (17, np.float64(0.05100410510067514)),
 (18, np.float64(0.025177841632809915)),
 (19, np.float64(0.11706383185253948)),
 (20, np.float64(0.0)),
 (21, np.float64(0.14333792815336935)),
 (22, np.float64(0.07847534327232125)),
 (23, np.float64(0.06150451339525138)),
 (24, np.float64(0.08723968326958673)),
 (25, np.float64(0.0)),
 (26, np.float64(0.07009814362931202)),
 (27, np.float64(0.13658680855472938)),
 (28, np.float64(0.07600327535501017)),
 (29, np.float64(0.12167133598776536)),
 (30, np.float64(0.007680459111722776)),
 (31, np.float64(0.01473221255132234)),
 (32, np.float64(0.0)),
 (33, np.float64(0.07965814289647455)),
 (34, np.float64(0.04522616573040869)),
 (35, np.float64(0.01556270914112474)),
 (36, np.float64(0.09495937740802216)),
 (37, np.float64(0.018230696811058135)),
 (38, np.float64(0.026104653172312028)),
 (39, np.float64(0.07984012108659384)),
 (40, np.float64(0.11679968613719668)),
 (41, np.float64(0.056912401804646934)),
 (42, np.float64(0.08354155383339157)),
 (43, np.float64(0.08471898090442946)),
 (44, np.float64(0.08785938150991274)),
 (45, np.float64(0.05491435163039676)),
 (46, np.float64(0.054850498513470236)),
 (47, np.float64(0.2702651417103732)),
 (48, np.float64(0.09779122591837028)),
 (49, np.float64(0.060160461842087495)),
 (50, np.float64(0.08958834926611466)),
 (51, np.float64(0.06748675491514017)),
 (52, np.float64(0.0)),
 (53, np.float64(0.044680983219421905)),
 (54, np.float64(0.019208718234636258)),
 (55, np.float64(0.0)),
 (56, np.float64(0.05629066845910846)),
 (57, np.float64(0.005579638588454276)),
 (58, np.float64(0.07877058635507732)),
 (59, np.float64(0.052194792200893965)),
 (60, np.float64(0.18908176672188648)),
 (61, np.float64(0.0)),
 (62, np.float64(0.012406560213354146)),
 (63, np.float64(0.029845724311982225)),
 (64, np.float64(0.04279501979786338)),
 (65, np.float64(0.12680124740531368)),
 (66, np.float64(0.16566734565340116)),
 (67, np.float64(0.0)),
 (68, np.float64(0.13357242093379193)),
 (69, np.float64(0.06615478064452682)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.1096807501418389)),
 (74, np.float64(0.02806606106883051)),
 (75, np.float64(0.04521795287053612)),
 (76, np.float64(0.02613276804655889)),
 (77, np.float64(0.06876130890656589)),
 (78, np.float64(0.013316271087745269)),
 (79, np.float64(0.10519138203342883)),
 (80, np.float64(0.03349456939792139)),
 (81, np.float64(0.013634576553468258)),
 (82, np.float64(0.23669374347400993)),
 (83, np.float64(0.0)),
 (84, np.float64(0.10397940924207362)),
 (85, np.float64(0.06167753120046458)),
 (86, np.float64(0.1417627291694863)),
 (87, np.float64(0.11661082872914152)),
 (88, np.float64(0.08331012208964667)),
 (89, np.float64(0.00850895140653615)),
 (90, np.float64(0.06715432766232284)),
 (91, np.float64(0.0)),
 (92, np.float64(0.15850821182810643)),
 (93, np.float64(0.03280520241000348)),
 (94, np.float64(0.010689154840164533)),
 (95, np.float64(0.025797824097510556)),
 (96, np.float64(0.02114858980511902)),
 (97, np.float64(0.02687778911799567)),
 (98, np.float64(0.02175821065382328)),
 (99, np.float64(0.0)),
 (100, np.float64(0.016016629607635186)),
 (101, np.float64(0.12114265984279052)),
 (102, np.float64(0.04768602689229997)),
 (103, np.float64(0.058191840680734276)),
 (104, np.float64(0.06510721558252526)),
 (105, np.float64(0.0)),
 (106, np.float64(0.047670497142785574)),
 (107, np.float64(0.05273164983675109)),
 (108, np.float64(0.02810009706063171)),
 (109, np.float64(0.06524573363186935)),
 (110, np.float64(0.021163446843373374)),
 (111, np.float64(0.02097867986921867)),
 (112, np.float64(0.07422249010392888)),
 (113, np.float64(0.017527779718968118)),
 (114, np.float64(0.03734566872286401)),
 (115, np.float64(0.0)),
 (116, np.float64(0.01579666260459111)),
 (117, np.float64(0.1103944810687539)),
 (118, np.float64(0.165272766123669)),
 (119, np.float64(0.15514318804365945)),
 (120, np.float64(0.06237453600241552)),
 (121, np.float64(0.08139488796880032)),
 (122, np.float64(0.056554138733275305)),
 (123, np.float64(0.07458202717929566)),
 (124, np.float64(0.03771888280719047)),
 (125, np.float64(0.059363300295016304)),
 (126, np.float64(0.02955369248311012)),
 (127, np.float64(0.03355602562283)),
 (128, np.float64(0.04734092759216691)),
 (129, np.float64(0.010066425112509755)),
 (130, np.float64(0.016719816747289874)),
 (131, np.float64(0.07258934796997447)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (135, np.float64(0.02428501142412964)),
 (136, np.float64(0.030678189040978528)),
 (137, np.float64(0.09974980034668827)),
 (138, np.float64(0.0)),
 (139, np.float64(0.016901518597837405)),
 (140, np.float64(0.024108621631248803)),
 (141, np.float64(0.028108399645259814)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (144, np.float64(0.0181287703514146)),
 (145, np.float64(0.028808272598853126)),
 (146, np.float64(0.0)),
 (147, np.float64(0.05995157134958024)),
 (148, np.float64(0.021276714965680187)),
 (149, np.float64(0.10341190148072846)),
 (150, np.float64(0.027667475691473428)),
 (151, np.float64(0.10684794535545848)),
 (152, np.float64(0.09898722239993361)),
 (153, np.float64(0.14145186155692357)),
 (154, np.float64(0.05007429159938883)),
 (155, np.float64(0.09428288870384942)),
 (156, np.float64(0.014112489355409683)),
 (157, np.float64(0.0)),
 (158, np.float64(0.07835976130061303)),
 (159, np.float64(0.00882242400686552)),
 (160, np.float64(0.04515898041752436)),
 (161, np.float64(0.0)),
 (162, np.float64(0.012814117802391826)),
 (163, np.float64(0.04003333547158616)),
 (164, np.float64(0.07477661367406771)),
 (165, np.float64(0.012179056920074677)),
 (166, np.float64(0.018873932015163516)),
 (167, np.float64(0.026674838717939867)),
 (168, np.float64(0.01432863977616057)),
 (169, np.float64(0.14702846562277322)),
 (170, np.float64(0.06087281632872059)),
 (171, np.float64(0.025783211586063344)),
 (172, np.float64(0.027418756526771074)),
 (173, np.float64(0.0)),
 (174, np.float64(0.14909595195082756)),
 (175, np.float64(0.05606788035530558)),
 (176, np.float64(0.0)),
 (177, np.float64(0.03199916313406436)),
 (178, np.float64(0.03643816906953526)),
 (179, np.float64(0.0)),
 (180, np.float64(0.01962921144060071)),
 (181, np.float64(0.22222254415660225)),
 (182, np.float64(0.015158449197584845)),
 (183, np.float64(0.09673267751838878)),
 (184, np.float64(0.02190023295408395)),
 (185, np.float64(0.020135489410098205)),
 (186, np.float64(0.05400331245399732)),
 (187, np.float64(0.07262017448772083)),
 (188, np.float64(0.011116365315772406)),
 (189, np.float64(0.036498718026030004)),
 (190, np.float64(0.05994663767295999)),
 (191, np.float64(0.0)),
 (192, np.float64(0.14691166711955864)),
 (193, np.float64(0.020860053643757807)),
 (194, np.float64(0.1035963528100001)),
 (195, np.float64(0.09794374510256892)),
 (196, np.float64(0.06609996896203728)),
 (197, np.float64(0.12871083086643306)),
 (198, np.float64(0.08992738703666601)),
 (199, np.float64(0.011474570339750256)),
 (200, np.float64(0.024601653277066596)),
 (201, np.float64(0.0)),
 (202, np.float64(0.18049207281616433)),
 (203, np.float64(0.05141892092902459)),
 (204, np.float64(0.047717402129725514)),
 (205, np.float64(0.10849696385128585)),
 (206, np.float64(0.1327813903167589)),
 (207, np.float64(0.059152881703632795)),
 (208, np.float64(0.053729841666378134)),
 (209, np.float64(0.034785003361519164)),
 (210, np.float64(0.0)),
 (211, np.float64(0.09203038690315052)),
 (212, np.float64(0.06388401351716998)),
 (213, np.float64(0.04773328410790857)),
 (214, np.float64(0.15570975499937129)),
 (215, np.float64(0.08420691059370962)),
 (216, np.float64(0.12338216998991305)),
 (217, np.float64(0.08784690368235953)),
 (218, np.float64(0.08205944603394638)),
 (219, np.float64(0.12177532243608828)),
 (220, np.float64(0.024337026385897676)),
 (221, np.float64(0.00272862336930817)),
 (222, np.float64(0.0)),
 (223, np.float64(0.0)),
 (224, np.float64(0.03671505063990275)),
 (225, np.float64(0.1528098402276361)),
 (226, np.float64(0.03709430441334803)),
 (227, np.float64(0.07458136399603107)),
 (228, np.float64(0.09746696979819942)),
 (229, np.float64(0.05416091103251691)),
 (230, np.float64(0.10266993316420167)),
 (231, np.float64(0.0757441443938586)),
 (232, np.float64(0.06426525769208898)),
 (233, np.float64(0.03601739518550193)),
 (234, np.float64(0.01559751952620105)),
 (235, np.float64(0.02033558874805688)),
 (236, np.float64(0.024635927968282654)),
 (237, np.float64(0.0)),
 (238, np.float64(0.03349154464789058)),
 (239, np.float64(0.021353685011361416)),
 (240, np.float64(0.019033695446023926)),
 (241, np.float64(0.06806264765162154)),
 (242, np.float64(0.020321161226731627)),
 (243, np.float64(0.11784705785247843)),
 (244, np.float64(0.07839488163675291)),
 (245, np.float64(0.08422557655984436)),
 (246, np.float64(0.0)),
 (247, np.float64(0.02040796206066411)),
 (248, np.float64(0.0)),
 (249, np.float64(0.046982457315643385)),
 (250, np.float64(0.08294512991462386)),
 (251, np.float64(0.13974513728492968)),
 (252, np.float64(0.012345246102533871)),
 (253, np.float64(0.1351060763800879)),
 (254, np.float64(0.07423488726781508)),
 (255, np.float64(0.1184188929166314)),
 (256, np.float64(0.049300912125160704)),
 (257, np.float64(0.016216682151444957)),
 (258, np.float64(0.026330228561191004)),
 (259, np.float64(0.04815971759587031)),
 (260, np.float64(0.019598256153707194)),
 (261, np.float64(0.10174252819190155)),
 (262, np.float64(0.13257638388225185)),
 (263, np.float64(0.0)),
 (264, np.float64(0.055102704646119355)),
 (265, np.float64(0.018611497829688243)),
 (266, np.float64(0.0)),
 (267, np.float64(0.04504597870526374)),
 (268, np.float64(0.03482458685305275)),
 (269, np.float64(0.1650329228149958)),
 (270, np.float64(0.08466191294337998)),
 (271, np.float64(0.06795352889900172)),
 (272, np.float64(0.029876534978291205)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.08781992709390865)),
 (276, np.float64(0.07885279086963545)),
 (277, np.float64(0.04799058127298857)),
 (278, np.float64(0.014679640011206505)),
 (279, np.float64(0.021238372796229556)),
 (280, np.float64(0.04549923467689111)),
 (281, np.float64(0.08673968616705958)),
 (282, np.float64(0.00885998445194921)),
 (283, np.float64(0.028806369616477166)),
 (284, np.float64(0.020221447157344582)),
 (285, np.float64(0.024141217209915328)),
 (286, np.float64(0.12548312467838352)),
 (287, np.float64(0.0)),
 (288, np.float64(0.02482518222135733)),
 (289, np.float64(0.06520605980064662)),
 (290, np.float64(0.0)),
 (291, np.float64(0.06069830203664196)),
 (292, np.float64(0.011778242975805127)),
 (293, np.float64(0.13974104783917973)),
 (294, np.float64(0.019788442258843547)),
 (295, np.float64(0.012608239194211564)),
 (296, np.float64(0.08608600626732467)),
 (297, np.float64(0.04433882752568145)),
 (298, np.float64(0.029430847399312027)),
 (299, np.float64(0.022424955017243866)),
 (300, np.float64(0.06541867556977009)),
 (301, np.float64(0.07866868132289853)),
 (302, np.float64(0.1428139852200272)),
 (303, np.float64(0.11979305199464946)),
 (304, np.float64(0.01858409288796079)),
 (305, np.float64(0.13445376799866068)),
 (306, np.float64(0.04809338200514574)),
 (307, np.float64(0.09790644477767069)),
 (308, np.float64(0.0)),
 (309, np.float64(0.17415730924332484)),
 (310, np.float64(0.07437756212042423)),
 (311, np.float64(0.0)),
 (312, np.float64(0.1238906533021012)),
 (313, np.float64(0.010423913217045038)),
 (314, np.float64(0.025808491020821493)),
 (315, np.float64(0.0)),
 (316, np.float64(0.08951389572154368)),
 (317, np.float64(0.04005551020725377)),
 (318, np.float64(0.19182230688281934)),
 (319, np.float64(0.02267512161790004)),
 (320, np.float64(0.017303468493582226)),
 (321, np.float64(0.03054044240047009)),
 (322, np.float64(0.0700882246357741)),
 (323, np.float64(0.10084626149563478)),
 (324, np.float64(0.10467615354986062)),
 (325, np.float64(0.016834621675675482)),
 (326, np.float64(0.12468283384023092)),
 (327, np.float64(0.10266459423639845)),
 (328, np.float64(0.035498355256648746)),
 (329, np.float64(0.026674838717939867)),
 (330, np.float64(0.07652764821891074)),
 (331, np.float64(0.08474055728984814)),
 (332, np.float64(0.018319772326554337)),
 (333, np.float64(0.021774817728178283)),
 (334, np.float64(0.15293362041446346)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.010632508151830204)),
 (338, np.float64(0.021530886296301118)),
 (339, np.float64(0.02946442510264468)),
 (340, np.float64(0.0)),
 (341, np.float64(0.020767833514212724)),
 (342, np.float64(0.011948245768325256)),
 (343, np.float64(0.009536746594659161)),
 (344, np.float64(0.20675540390453995)),
 (345, np.float64(0.015542921836058245)),
 (346, np.float64(0.03902659506471766)),
 (347, np.float64(0.06681045925540752)),
 (348, np.float64(0.09014973218560088)),
 (349, np.float64(0.05914734917065386)),
 (350, np.float64(0.06206857320564754)),
 (351, np.float64(0.0)),
 (352, np.float64(0.020059585724360268)),
 (353, np.float64(0.07843565693314272)),
 (354, np.float64(0.16337845332530374)),
 (355, np.float64(0.07161075491687474)),
 (356, np.float64(0.0)),
 (357, np.float64(0.1459525808785892)),
 (358, np.float64(0.07561631141753603)),
 (359, np.float64(0.029397384230560795)),
 (360, np.float64(0.047796293241950796)),
 (361, np.float64(0.018072383204619496)),
 (362, np.float64(0.11362722122094872)),
 (363, np.float64(0.09791273187403501)),
 (364, np.float64(0.07999692625971765)),
 (365, np.float64(0.0891233745026412)),
 (366, np.float64(0.10941777035919222)),
 (367, np.float64(0.0)),
 (368, np.float64(0.02115842407200956)),
 (369, np.float64(0.060039300152930415)),
 (370, np.float64(0.017971540540139944)),
 (371, np.float64(0.05755407693373189)),
 (372, np.float64(0.021668631362692693)),
 (373, np.float64(0.09754449459555777)),
 (374, np.float64(0.13107651944057502)),
 (375, np.float64(0.0)),
 (376, np.float64(0.06829903941402894)),
 (377, np.float64(0.09132921952528268)),
 (378, np.float64(0.0)),
 (379, np.float64(0.02781406274224919)),
 (380, np.float64(0.015333681815045101)),
 (381, np.float64(0.06113178628791212)),
 (382, np.float64(0.017572862308732076)),
 (383, np.float64(0.024712941476041382)),
 (384, np.float64(0.018015801292409934)),
 (385, np.float64(0.1178980615083171)),
 (386, np.float64(0.06468143253238315)),
 (387, np.float64(0.1390419059870689)),
 (388, np.float64(0.0)),
 (389, np.float64(0.06671644037106779)),
 (390, np.float64(0.0)),
 (391, np.float64(0.0)),
 (392, np.float64(0.057620863815487075)),
 (393, np.float64(0.02266096293926825)),
 (394, np.float64(0.008448763927099017)),
 (395, np.float64(0.02297481006625077)),
 (396, np.float64(0.07136276113078666)),
 (397, np.float64(0.1530551446766823)),
 (398, np.float64(0.06039873575147915)),
 (399, np.float64(0.0)),
 (400, np.float64(0.08996912406728536)),
 (401, np.float64(0.015459465622161536)),
 (402, np.float64(0.10135299399598713)),
 (403, np.float64(0.0)),
 (404, np.float64(0.016763442237401817)),
 (405, np.float64(0.0)),
 (406, np.float64(0.05021880312673623)),
 (407, np.float64(0.16041182196659062)),
 (408, np.float64(0.0)),
 (409, np.float64(0.1343973311768824)),
 (410, np.float64(0.12508513698245888)),
 (411, np.float64(0.02329035016031528)),
 (412, np.float64(0.019872703940133213)),
 (413, np.float64(0.011056735115042383)),
 (414, np.float64(0.025480338679592467)),
 (415, np.float64(0.0089604367821904)),
 (416, np.float64(0.0824612198578452)),
 (417, np.float64(0.01902896010686717)),
 (418, np.float64(0.07025002832914887)),
 (419, np.float64(0.021636698437203145)),
 (420, np.float64(0.12822981990037824)),
 (421, np.float64(0.0999877199669616)),
 (422, np.float64(0.08642894687915843)),
 (423, np.float64(0.0635519690782283)),
 (424, np.float64(0.028830240654024085)),
 (425, np.float64(0.04335826491498011)),
 (426, np.float64(0.04706590154362337)),
 (427, np.float64(0.0522373263993224)),
 (428, np.float64(0.0)),
 (429, np.float64(0.08982750671022352)),
 (430, np.float64(0.00875634332679306)),
 (431, np.float64(0.09923541776574221)),
 (432, np.float64(0.10228551050235933)),
 (433, np.float64(0.0)),
 (434, np.float64(0.12307492189941618)),
 (435, np.float64(0.01758928833928951)),
 (436, np.float64(0.020281245334279798)),
 (437, np.float64(0.1033826953037451)),
 (438, np.float64(0.130281708532021)),
 (439, np.float64(0.08988894455657523)),
 (440, np.float64(0.09005001295005992)),
 (441, np.float64(0.05332049434044375)),
 (442, np.float64(0.08033435626539932)),
 (443, np.float64(0.045977952103493924)),
 (444, np.float64(0.061398875647666676)),
 (445, np.float64(0.023007092325074995)),
 (446, np.float64(0.023049037833599993)),
 (447, np.float64(0.06523041320455897)),
 (448, np.float64(0.01915362558614925)),
 (449, np.float64(0.0)),
 (450, np.float64(0.04542765998492866)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.05261953990010256)),
 (454, np.float64(0.01317087876205714)),
 (455, np.float64(0.0)),
 (456, np.float64(0.0)),
 (457, np.float64(0.048593102089385304)),
 (458, np.float64(0.07348190409223959)),
 (459, np.float64(0.10354480865656568)),
 (460, np.float64(0.0171880657878069)),
 (461, np.float64(0.09919937023309428)),
 (462, np.float64(0.08091989315700655)),
 (463, np.float64(0.0035883533320389396)),
 (464, np.float64(0.04757132169040053)),
 (465, np.float64(0.11122764671322921)),
 (466, np.float64(0.051434806536338154)),
 (467, np.float64(0.05666140304625101)),
 (468, np.float64(0.0)),
 (469, np.float64(0.060877194204984726)),
 (470, np.float64(0.10800615252570414)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0755468596127809)),
 (473, np.float64(0.0)),
 (474, np.float64(0.13644383961641227)),
 (475, np.float64(0.04796762686649386)),
 (476, np.float64(0.16104067376144765)),
 (477, np.float64(0.0)),
 (478, np.float64(0.017598641856748937)),
 (479, np.float64(0.05438295377092604)),
 (480, np.float64(0.0)),
 (481, np.float64(0.08100800937525751)),
 (482, np.float64(0.13090710604063543)),
 (483, np.float64(0.00581843892000093)),
 (484, np.float64(0.07150547342980032)),
 (485, np.float64(0.05428487095514969)),
 (486, np.float64(0.06143184266443724)),
 (487, np.float64(0.051616531477964966)),
 (488, np.float64(0.19511819825564608)),
 (489, np.float64(0.1149487959814155)),
 (490, np.float64(0.06513046875777172)),
 (491, np.float64(0.06401961292305569)),
 (492, np.float64(0.0)),
 (493, np.float64(0.0)),
 (494, np.float64(0.10853661984252007)),
 (495, np.float64(0.11400426236261282)),
 (496, np.float64(0.046392498261486066)),
 (497, np.float64(0.018252769789423258)),
 (498, np.float64(0.0)),
 (499, np.float64(0.011952011165403655)),
 (500, np.float64(0.21057743765309012)),
 (501, np.float64(0.058097069301565475)),
 (502, np.float64(0.043491562429456586)),
 (503, np.float64(0.02646255704581015)),
 (504, np.float64(0.07276403383736725)),
 (505, np.float64(0.05264856975654457)),
 (506, np.float64(0.07242165076731459)),
 (507, np.float64(0.06790897506872169)),
 (508, np.float64(0.016265641643564675)),
 (509, np.float64(0.024318094429406693)),
 (510, np.float64(0.020935646634428463)),
 (511, np.float64(0.13617057407600314)),
 (512, np.float64(0.11784149206441577)),
 (513, np.float64(0.08588206473402643)),
 (514, np.float64(0.0928435169211848)),
 (515, np.float64(0.11277296885857815)),
 (516, np.float64(0.06868983304237651)),

In [47]:
# sorted based on similarity score
sorted(list(enumerate(similarity_scores[0])),key=lambda x:x[1],reverse=True)

[(0, np.float64(0.9999999999999998)),
 (47, np.float64(0.2702651417103732)),
 (545, np.float64(0.2639619371123497)),
 (82, np.float64(0.23669374347400993)),
 (634, np.float64(0.23299389358170394)),
 (551, np.float64(0.2262639743141286)),
 (181, np.float64(0.22222254415660225)),
 (500, np.float64(0.21057743765309012)),
 (344, np.float64(0.20675540390453995)),
 (554, np.float64(0.20025063706783053)),
 (520, np.float64(0.19972624710300058)),
 (527, np.float64(0.19656287691544358)),
 (488, np.float64(0.19511819825564608)),
 (552, np.float64(0.1920889620576415)),
 (318, np.float64(0.19182230688281934)),
 (624, np.float64(0.1892531370760997)),
 (598, np.float64(0.189213677823462)),
 (60, np.float64(0.18908176672188648)),
 (622, np.float64(0.18571699439818884)),
 (647, np.float64(0.1841081817659337)),
 (546, np.float64(0.18408910419891056)),
 (202, np.float64(0.18049207281616433)),
 (541, np.float64(0.17990898085771034)),
 (309, np.float64(0.17415730924332484)),
 (588, np.float64(0.1738182944100774)),
 (537, np.float64(0.1700871998622835)),
 (544, np.float64(0.1672877700938274)),
 (66, np.float64(0.16566734565340116)),
 (118, np.float64(0.165272766123669)),
 (269, np.float64(0.1650329228149958)),
 (354, np.float64(0.16337845332530374)),
 (476, np.float64(0.16104067376144765)),
 (407, np.float64(0.16041182196659062)),
 (590, np.float64(0.16000267935045498)),
 (666, np.float64(0.1589387141616799)),
 (92, np.float64(0.15850821182810643)),
 (214, np.float64(0.15570975499937129)),
 (119, np.float64(0.15514318804365945)),
 (569, np.float64(0.15344079020689355)),
 (397, np.float64(0.1530551446766823)),
 (334, np.float64(0.15293362041446346)),
 (225, np.float64(0.1528098402276361)),
 (576, np.float64(0.15211972188253267)),
 (174, np.float64(0.14909595195082756)),
 (169, np.float64(0.14702846562277322)),
 (192, np.float64(0.14691166711955864)),
 (591, np.float64(0.14681485749917436)),
 (357, np.float64(0.1459525808785892)),
 (550, np.float64(0.1445684727872654)),
 (643, np.float64(0.1444555917585842)),
 (659, np.float64(0.14444516556944695)),
 (638, np.float64(0.14440017099395475)),
 (583, np.float64(0.14421330855040418)),
 (21, np.float64(0.14333792815336935)),
 (302, np.float64(0.1428139852200272)),
 (558, np.float64(0.1420165983985733)),
 (86, np.float64(0.1417627291694863)),
 (153, np.float64(0.14145186155692357)),
 (251, np.float64(0.13974513728492968)),
 (293, np.float64(0.13974104783917973)),
 (387, np.float64(0.1390419059870689)),
 (7, np.float64(0.13732869060263378)),
 (27, np.float64(0.13658680855472938)),
 (474, np.float64(0.13644383961641227)),
 (511, np.float64(0.13617057407600314)),
 (636, np.float64(0.13573542468856645)),
 (253, np.float64(0.1351060763800879)),
 (305, np.float64(0.13445376799866068)),
 (409, np.float64(0.1343973311768824)),
 (14, np.float64(0.13388864701187034)),
 (518, np.float64(0.13369059478865902)),
 (674, np.float64(0.13365875731715246)),
 (68, np.float64(0.13357242093379193)),
 (206, np.float64(0.1327813903167589)),
 (262, np.float64(0.13257638388225185)),
 (374, np.float64(0.13107651944057502)),
 (482, np.float64(0.13090710604063543)),
 (438, np.float64(0.130281708532021)),
 (197, np.float64(0.12871083086643306)),
 (606, np.float64(0.12858515029485706)),
 (420, np.float64(0.12822981990037824)),
 (562, np.float64(0.1279402426979562)),
 (65, np.float64(0.12680124740531368)),
 (682, np.float64(0.1265536444037226)),
 (286, np.float64(0.12548312467838352)),
 (699, np.float64(0.12530648498478347)),
 (640, np.float64(0.12522954271046702)),
 (410, np.float64(0.12508513698245888)),
 (326, np.float64(0.12468283384023092)),
 (312, np.float64(0.1238906533021012)),
 (660, np.float64(0.12340233502840114)),
 (216, np.float64(0.12338216998991305)),
 (557, np.float64(0.12333680291383342)),
 (434, np.float64(0.12307492189941618)),
 (219, np.float64(0.12177532243608828)),
 (29, np.float64(0.12167133598776536)),
 (101, np.float64(0.12114265984279052)),
 (703, np.float64(0.12110366748083307)),
 (627, np.float64(0.12024780353669523)),
 (303, np.float64(0.11979305199464946)),
 (255, np.float64(0.1184188929166314)),
 (385, np.float64(0.1178980615083171)),
 (243, np.float64(0.11784705785247843)),
 (512, np.float64(0.11784149206441577)),
 (19, np.float64(0.11706383185253948)),
 (40, np.float64(0.11679968613719668)),
 (87, np.float64(0.11661082872914152)),
 (489, np.float64(0.1149487959814155)),
 (604, np.float64(0.1144539948977886)),
 (495, np.float64(0.11400426236261282)),
 (362, np.float64(0.11362722122094872)),
 (515, np.float64(0.11277296885857815)),
 (16, np.float64(0.1115354275858341)),
 (465, np.float64(0.11122764671322921)),
 (117, np.float64(0.1103944810687539)),
 (649, np.float64(0.1099076405115528)),
 (73, np.float64(0.1096807501418389)),
 (366, np.float64(0.10941777035919222)),
 (494, np.float64(0.10853661984252007)),
 (650, np.float64(0.10850377176901972)),
 (205, np.float64(0.10849696385128585)),
 (470, np.float64(0.10800615252570414)),
 (612, np.float64(0.10725981836116358)),
 (151, np.float64(0.10684794535545848)),
 (630, np.float64(0.10596223905942811)),
 (79, np.float64(0.10519138203342883)),
 (324, np.float64(0.10467615354986062)),
 (84, np.float64(0.10397940924207362)),
 (194, np.float64(0.1035963528100001)),
 (459, np.float64(0.10354480865656568)),
 (149, np.float64(0.10341190148072846)),
 (437, np.float64(0.1033826953037451)),
 (578, np.float64(0.10307399310158656)),
 (230, np.float64(0.10266993316420167)),
 (611, np.float64(0.10266590131312461)),
 (327, np.float64(0.10266459423639845)),
 (1, np.float64(0.10255024829874466)),
 (432, np.float64(0.10228551050235933)),
 (261, np.float64(0.10174252819190155)),
 (402, np.float64(0.10135299399598713)),
 (323, np.float64(0.10084626149563478)),
 (421, np.float64(0.0999877199669616)),
 (670, np.float64(0.09993168845101595)),
 (137, np.float64(0.09974980034668827)),
 (431, np.float64(0.09923541776574221)),
 (461, np.float64(0.09919937023309428)),
 (152, np.float64(0.09898722239993361)),
 (615, np.float64(0.0987294045857185)),
 (628, np.float64(0.09840359079895453)),
 (620, np.float64(0.09797466122629746)),
 (195, np.float64(0.09794374510256892)),
 (363, np.float64(0.09791273187403501)),
 (307, np.float64(0.09790644477767069)),
 (48, np.float64(0.09779122591837028)),
 (574, np.float64(0.09772941568150427)),
 (373, np.float64(0.09754449459555777)),
 (228, np.float64(0.09746696979819942)),
 (13, np.float64(0.09673734976610586)),
 (183, np.float64(0.09673267751838878)),
 (531, np.float64(0.09596456280564838)),
 (565, np.float64(0.09532519178944057)),
 (645, np.float64(0.09508161331593905)),
 (36, np.float64(0.09495937740802216)),
 (672, np.float64(0.09488374038474037)),
 (155, np.float64(0.09428288870384942)),
 (514, np.float64(0.0928435169211848)),
 (211, np.float64(0.09203038690315052)),
 (377, np.float64(0.09132921952528268)),
 (684, np.float64(0.09095705260744957)),
 (348, np.float64(0.09014973218560088)),
 (440, np.float64(0.09005001295005992)),
 (400, np.float64(0.08996912406728536)),
 (198, np.float64(0.08992738703666601)),
 (439, np.float64(0.08988894455657523)),
 (429, np.float64(0.08982750671022352)),
 (50, np.float64(0.08958834926611466)),
 (316, np.float64(0.08951389572154368)),
 (365, np.float64(0.0891233745026412)),
 (665, np.float64(0.08904275766583061)),
 (570, np.float64(0.0885630163776942)),
 (44, np.float64(0.08785938150991274)),
 (217, np.float64(0.08784690368235953)),
 (275, np.float64(0.08781992709390865)),
 (24, np.float64(0.08723968326958673)),
 (648, np.float64(0.08704223712018071)),
 (281, np.float64(0.08673968616705958)),
 (422, np.float64(0.08642894687915843)),
 (296, np.float64(0.08608600626732467)),
 (513, np.float64(0.08588206473402643)),
 (560, np.float64(0.08563805381851426)),
 (540, np.float64(0.08541217689607684)),
 (331, np.float64(0.08474055728984814)),
 (43, np.float64(0.08471898090442946)),
 (270, np.float64(0.08466191294337998)),
 (245, np.float64(0.08422557655984436)),
 (215, np.float64(0.08420691059370962)),
 (683, np.float64(0.08418288167449578)),
 (689, np.float64(0.0839284865111645)),
 (42, np.float64(0.08354155383339157)),
 (88, np.float64(0.08331012208964667)),
 (15, np.float64(0.0830311169181103)),
 (250, np.float64(0.08294512991462386)),
 (536, np.float64(0.08280451731096075)),
 (584, np.float64(0.08272478073987326)),
 (416, np.float64(0.0824612198578452)),
 (6, np.float64(0.08216491130000354)),
 (218, np.float64(0.08205944603394638)),
 (517, np.float64(0.08200947294838494)),
 (686, np.float64(0.08143881222401984)),
 (121, np.float64(0.08139488796880032)),
 (481, np.float64(0.08100800937525751)),
 (462, np.float64(0.08091989315700655)),
 (616, np.float64(0.0807748212690039)),
 (522, np.float64(0.08062879942666365)),
 (632, np.float64(0.0805438980307519)),
 (442, np.float64(0.08033435626539932)),
 (542, np.float64(0.08007284499901246)),
 (605, np.float64(0.08001595368794218)),
 (364, np.float64(0.07999692625971765)),
 (39, np.float64(0.07984012108659384)),
 (33, np.float64(0.07965814289647455)),
 (276, np.float64(0.07885279086963545)),
 (58, np.float64(0.07877058635507732)),
 (301, np.float64(0.07866868132289853)),
 (22, np.float64(0.07847534327232125)),
 (654, np.float64(0.07845404559691257)),
 (353, np.float64(0.07843565693314272)),
 (244, np.float64(0.07839488163675291)),
 (158, np.float64(0.07835976130061303)),
 (690, np.float64(0.07785800873431292)),
 (594, np.float64(0.07725115117942094)),
 (330, np.float64(0.07652764821891074)),
 (631, np.float64(0.07617194789896939)),
 (28, np.float64(0.07600327535501017)),
 (231, np.float64(0.0757441443938586)),
 (358, np.float64(0.07561631141753603)),
 (472, np.float64(0.0755468596127809)),
 (164, np.float64(0.07477661367406771)),
 (595, np.float64(0.07464762808145006)),
 (123, np.float64(0.07458202717929566)),
 (227, np.float64(0.07458136399603107)),
 (310, np.float64(0.07437756212042423)),
 (254, np.float64(0.07423488726781508)),
 (112, np.float64(0.07422249010392888)),
 (664, np.float64(0.07391777683093743)),
 (564, np.float64(0.07352435567112062)),
 (458, np.float64(0.07348190409223959)),
 (704, np.float64(0.07347566833900478)),
 (504, np.float64(0.07276403383736725)),
 (187, np.float64(0.07262017448772083)),
 (131, np.float64(0.07258934796997447)),
 (506, np.float64(0.07242165076731459)),
 (538, np.float64(0.07213921021695388)),
 (567, np.float64(0.0719421185191427)),
 (355, np.float64(0.07161075491687474)),
 (692, np.float64(0.07151793939760115)),
 (484, np.float64(0.07150547342980032)),
 (396, np.float64(0.07136276113078666)),
 (535, np.float64(0.07052240553428667)),
 (418, np.float64(0.07025002832914887)),
 (597, np.float64(0.07021576771146076)),
 (26, np.float64(0.07009814362931202)),
 (322, np.float64(0.0700882246357741)),
 (667, np.float64(0.06947573726333098)),
 (549, np.float64(0.0691101496608291)),
 (77, np.float64(0.06876130890656589)),
 (516, np.float64(0.06868983304237651)),
 (376, np.float64(0.06829903941402894)),
 (241, np.float64(0.06806264765162154)),
 (271, np.float64(0.06795352889900172)),
 (507, np.float64(0.06790897506872169)),
 (11, np.float64(0.06766486753662343)),
 (51, np.float64(0.06748675491514017)),
 (525, np.float64(0.06738056011305654)),
 (677, np.float64(0.0672128392842741)),
 (90, np.float64(0.06715432766232284)),
 (347, np.float64(0.06681045925540752)),
 (389, np.float64(0.06671644037106779)),
 (69, np.float64(0.06615478064452682)),
 (196, np.float64(0.06609996896203728)),
 (582, np.float64(0.06572303470837207)),
 (596, np.float64(0.06546695823953794)),
 (300, np.float64(0.06541867556977009)),
 (109, np.float64(0.06524573363186935)),
 (447, np.float64(0.06523041320455897)),
 (289, np.float64(0.06520605980064662)),
 (490, np.float64(0.06513046875777172)),
 (104, np.float64(0.06510721558252526)),
 (534, np.float64(0.06476148889541151)),
 (386, np.float64(0.06468143253238315)),
 (641, np.float64(0.06455010070487521)),
 (232, np.float64(0.06426525769208898)),
 (491, np.float64(0.06401961292305569)),
 (212, np.float64(0.06388401351716998)),
 (423, np.float64(0.0635519690782283)),
 (528, np.float64(0.06306425554305625)),
 (581, np.float64(0.06303898971663935)),
 (120, np.float64(0.06237453600241552)),
 (350, np.float64(0.06206857320564754)),
 (85, np.float64(0.06167753120046458)),
 (23, np.float64(0.06150451339525138)),
 (486, np.float64(0.06143184266443724)),
 (444, np.float64(0.061398875647666676)),
 (608, np.float64(0.06129105448105361)),
 (530, np.float64(0.06123118935155921)),
 (381, np.float64(0.06113178628791212)),
 (469, np.float64(0.060877194204984726)),
 (170, np.float64(0.06087281632872059)),
 (291, np.float64(0.06069830203664196)),
 (398, np.float64(0.06039873575147915)),
 (49, np.float64(0.060160461842087495)),
 (369, np.float64(0.060039300152930415)),
 (147, np.float64(0.05995157134958024)),
 (190, np.float64(0.05994663767295999)),
 (593, np.float64(0.05940546334243634)),
 (125, np.float64(0.059363300295016304)),
 (207, np.float64(0.059152881703632795)),
 (349, np.float64(0.05914734917065386)),
 (625, np.float64(0.05894189200911533)),
 (701, np.float64(0.05864096359154978)),
 (103, np.float64(0.058191840680734276)),
 (501, np.float64(0.058097069301565475)),
 (675, np.float64(0.057940637804840725)),
 (392, np.float64(0.057620863815487075)),
 (524, np.float64(0.057560148077814344)),
 (371, np.float64(0.05755407693373189)),
 (579, np.float64(0.057157891413611744)),
 (671, np.float64(0.05711356172333468)),
 (41, np.float64(0.056912401804646934)),
 (467, np.float64(0.05666140304625101)),
 (122, np.float64(0.056554138733275305)),
 (56, np.float64(0.05629066845910846)),
 (175, np.float64(0.05606788035530558)),
 (547, np.float64(0.05600272988869)),
 (264, np.float64(0.055102704646119355)),
 (45, np.float64(0.05491435163039676)),
 (46, np.float64(0.054850498513470236)),
 (479, np.float64(0.05438295377092604)),
 (601, np.float64(0.05437622462310082)),
 (485, np.float64(0.05428487095514969)),
 (229, np.float64(0.05416091103251691)),
 (186, np.float64(0.05400331245399732)),
 (208, np.float64(0.053729841666378134)),
 (4, np.float64(0.053672244225442485)),
 (623, np.float64(0.053445774200822666)),
 (441, np.float64(0.05332049434044375)),
 (107, np.float64(0.05273164983675109)),
 (505, np.float64(0.05264856975654457)),
 (453, np.float64(0.05261953990010256)),
 (696, np.float64(0.05237226614377158)),
 (427, np.float64(0.0522373263993224)),
 (59, np.float64(0.052194792200893965)),
 (646, np.float64(0.05179020017229585)),
 (487, np.float64(0.051616531477964966)),
 (556, np.float64(0.05144282019851702)),
 (466, np.float64(0.051434806536338154)),
 (203, np.float64(0.05141892092902459)),
 (17, np.float64(0.05100410510067514)),
 (406, np.float64(0.05021880312673623)),
 (154, np.float64(0.05007429159938883)),
 (602, np.float64(0.04932819154504025)),
 (256, np.float64(0.049300912125160704)),
 (457, np.float64(0.048593102089385304)),
 (259, np.float64(0.04815971759587031)),
 (306, np.float64(0.04809338200514574)),
 (277, np.float64(0.04799058127298857)),
 (475, np.float64(0.04796762686649386)),
 (360, np.float64(0.047796293241950796)),
 (213, np.float64(0.04773328410790857)),
 (204, np.float64(0.047717402129725514)),
 (102, np.float64(0.04768602689229997)),
 (106, np.float64(0.047670497142785574)),
 (464, np.float64(0.04757132169040053)),
 (128, np.float64(0.04734092759216691)),
 (426, np.float64(0.04706590154362337)),
 (249, np.float64(0.046982457315643385)),
 (496, np.float64(0.046392498261486066)),
 (580, np.float64(0.046000562607200646)),
 (443, np.float64(0.045977952103493924)),
 (637, np.float64(0.045785523306335146)),
 (610, np.float64(0.04550867061591275)),
 (280, np.float64(0.04549923467689111)),
 (450, np.float64(0.04542765998492866)),
 (34, np.float64(0.04522616573040869)),
 (75, np.float64(0.04521795287053612)),
 (160, np.float64(0.04515898041752436)),
 (267, np.float64(0.04504597870526374)),
 (53, np.float64(0.044680983219421905)),
 (297, np.float64(0.04433882752568145)),
 (575, np.float64(0.044043586511889346)),
 (502, np.float64(0.043491562429456586)),
 (425, np.float64(0.04335826491498011)),
 (705, np.float64(0.04316045784191231)),
 (64, np.float64(0.04279501979786338)),
 (658, np.float64(0.04223674045619745)),
 (688, np.float64(0.042188025333763236)),
 (586, np.float64(0.04203701143606598)),
 (548, np.float64(0.04133585716291763)),
 (317, np.float64(0.04005551020725377)),
 (163, np.float64(0.04003333547158616)),
 (651, np.float64(0.03954864515701187)),
 (346, np.float64(0.03902659506471766)),
 (652, np.float64(0.03836309816637586)),
 (124, np.float64(0.03771888280719047)),
 (114, np.float64(0.03734566872286401)),
 (695, np.float64(0.03734566872286401)),
 (226, np.float64(0.03709430441334803)),
 (224, np.float64(0.03671505063990275)),
 (9, np.float64(0.03667590746512177)),
 (189, np.float64(0.036498718026030004)),
 (178, np.float64(0.03643816906953526)),
 (233, np.float64(0.03601739518550193)),
 (328, np.float64(0.035498355256648746)),
 (529, np.float64(0.03499381360818396)),
 (268, np.float64(0.03482458685305275)),
 (209, np.float64(0.034785003361519164)),
 (655, np.float64(0.03455547895208963)),
 (566, np.float64(0.03421894679431926)),
 (127, np.float64(0.03355602562283)),
 (80, np.float64(0.03349456939792139)),
 (238, np.float64(0.03349154464789058)),
 (93, np.float64(0.03280520241000348)),
 (8, np.float64(0.03261686350494277)),
 (177, np.float64(0.03199916313406436)),
 (136, np.float64(0.030678189040978528)),
 (321, np.float64(0.03054044240047009)),
 (656, np.float64(0.030076807297674774)),
 (272, np.float64(0.029876534978291205)),
 (63, np.float64(0.029845724311982225)),
 (126, np.float64(0.02955369248311012)),
 (339, np.float64(0.02946442510264468)),
 (298, np.float64(0.029430847399312027)),
 (359, np.float64(0.029397384230560795)),
 (424, np.float64(0.028830240654024085)),
 (145, np.float64(0.028808272598853126)),
 (283, np.float64(0.028806369616477166)),
 (662, np.float64(0.028443700563612766)),
 (642, np.float64(0.02817521704586765)),
 (141, np.float64(0.028108399645259814)),
 (108, np.float64(0.02810009706063171)),
 (74, np.float64(0.02806606106883051)),
 (379, np.float64(0.02781406274224919)),
 (5, np.float64(0.027749013024662858)),
 (150, np.float64(0.027667475691473428)),
 (172, np.float64(0.027418756526771074)),
 (97, np.float64(0.02687778911799567)),
 (167, np.float64(0.026674838717939867)),
 (329, np.float64(0.026674838717939867)),
 (503, np.float64(0.02646255704581015)),
 (258, np.float64(0.026330228561191004)),
 (76, np.float64(0.02613276804655889)),
 (38, np.float64(0.026104653172312028)),
 (613, np.float64(0.026053401473749117)),
 (314, np.float64(0.025808491020821493)),
 (95, np.float64(0.025797824097510556)),
 (171, np.float64(0.025783211586063344)),
 (414, np.float64(0.025480338679592467)),
 (18, np.float64(0.025177841632809915)),
 (599, np.float64(0.02494136129371724)),
 (657, np.float64(0.024840764583155147)),
 (288, np.float64(0.02482518222135733)),
 (559, np.float64(0.024720785609384784)),
 (383, np.float64(0.024712941476041382)),
 (236, np.float64(0.024635927968282654)),
 (653, np.float64(0.02463490862737704)),
 (200, np.float64(0.024601653277066596)),
 (220, np.float64(0.024337026385897676)),
 (509, np.float64(0.024318094429406693)),
 (135, np.float64(0.02428501142412964)),
 (285, np.float64(0.024141217209915328)),
 (140, np.float64(0.024108621631248803)),
 (693, np.float64(0.02407593195976403)),
 (553, np.float64(0.023933399289577127)),
 (561, np.float64(0.023634261138311616)),
 (411, np.float64(0.02329035016031528)),
 (10, np.float64(0.02322418425912186)),
 (533, np.float64(0.023175154774464087)),
 (607, np.float64(0.023066582966561253)),
 (446, np.float64(0.023049037833599993)),
 (445, np.float64(0.023007092325074995)),
 (395, np.float64(0.02297481006625077)),
 (568, np.float64(0.022970785411852147)),
 (521, np.float64(0.0228620664348094)),
 (587, np.float64(0.022760772453994885)),
 (319, np.float64(0.02267512161790004)),
 (393, np.float64(0.02266096293926825)),
 (299, np.float64(0.022424955017243866)),
 (184, np.float64(0.02190023295408395)),
 (532, np.float64(0.021801683645525486)),

In [48]:
# similar book top 1 to 6
sorted(list(enumerate(similarity_scores[0])),key=lambda x:x[1],reverse=True)[1:6]

[(47, np.float64(0.2702651417103732)),
 (545, np.float64(0.2639619371123497)),
 (82, np.float64(0.23669374347400993)),
 (634, np.float64(0.23299389358170394)),
 (551, np.float64(0.2262639743141286))]

In [49]:
pt.index.get_loc('Zoya')

704

# create function for recommend

In [50]:
np.where(pt.index=='Zoya')[0][0]

np.int64(704)

In [51]:
np.where(pt.index=='1984')[0][0] # find the book index

np.int64(0)

In [52]:
# create function for recommendation

def recommend(book_name):
  index = np.where(pt.index==book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]

  for i in similar_items:
    print(pt.index[i[0]])

In [53]:
recommend('Wuthering Heights')

The Thorn Birds
Primary Colors: A Novel of Politics
Dances With Wolves
Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies
Pleading Guilty

In [54]:
recommend('Zoya')

Fine Things
Secrets
Kaleidoscope
Exclusive
Five Days in Paris

In [55]:
recommend('1984')

Animal Farm
The Handmaid's Tale
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel

# image url

In [56]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

In [ ]:
# pickle

In [57]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))